#!/bin/sh

set -eux

cd "$(dirname "${0}")/../"

if [ "$(uname -s)" = "Darwin" ]; then
    if [ ! -x "/usr/local/bin/docker" ]; then
        # Assume that the user installed Docker for Mac Beta if the 'docker' binary is there.
        brew install docker docker-machine
    fi

    brew cask install desmume sox
elif [ -x "$(which lsb_release)" ] && [ "$(lsb_release -is)" = "Ubuntu" ]; then
    sudo apt install -y desmume docker.io
fi
