#!/bin/bash

set -euo pipefail
IFS=$'\n\t'
cd "$(cd "$(dirname "${0}")"; pwd)/../"

if [[ "$(uname -s)" == "Darwin" ]]; then
    brew install docker docker-machine

    brew cask install desmume
elif [[ -x "$(which lsb_release)" && "$(lsb_release -is)" == "Ubuntu" ]]; then
    sudo apt install -y desmume docker.io
fi
