#!/bin/sh
# -*- sh -*-

set -eux

cd "$(dirname "${0}")/../"

if tty -s; then
    TTY=1
fi

docker run \
    --volume="$(pwd):/home/code" \
    ${TTY+--interactive} ${TTY+--tty} \
    develhack:latest \
    sh -c "./waf configure build"
