#!/bin/bash

set -euo pipefail
IFS=$'\n\t'
cd "$(cd "$(dirname "${0}")"; pwd)/../"

docker_run() {
    docker run -it -v "$(pwd):/home/code" develhack:latest sh -c "${@}"
}

if [[ ! -d "build" ]]; then
    mkdir -p build
    docker_run "cd build && cmake .."
fi

docker_run "cd build && make"
