#!/bin/sh

set -eu

cd "$(dirname "${0}")/../" || exit 1

if [ "${#}" -lt 1 ]; then
    echo "Usage: ${0} <data.img> input1 input2 ..."
    exit 1
fi

OUT="${1}"
shift 1

#
# Create Image
#

mformat -C -t 1 -h 1 -s 512 -i "${OUT}"

#
# Populate Disk Image
#

mcopy -i "${OUT}" "${@}" ::
mdir -i "${OUT}"
