#!/bin/sh

set -eu

cd "$(dirname "${0}")/../" || exit 1

if [ "${#}" -lt 1 ]; then
    echo "Usage: ${0} <data.img> input1 input2 ..."
    exit 1
fi

OUT="${1}"
shift 1

#
# Cleanup
#

on_exit() {
    umount /mnt || true
}

trap on_exit EXIT

#
# Create Image
#

dd if=/dev/zero of="${OUT}" bs=1K count=256
mkfs.vfat "${OUT}"
mount -o loop "${OUT}" /mnt

#
# Populate Disk Image
#

cp "${@}" /mnt/
ls -l /mnt/
