#!/bin/bash

set -euo pipefail
IFS=$'\n\t'
cd "$(cd "$(dirname "${0}")"; pwd)/../"

if [[ ! -x "$(which desmume)" ]]; then
	echo "Please install desmume first. Aborting."
	exit 1
fi

exec desmume --load-type=1 --cflash-path=data build/game.nds